---
- set_fact:
    real_ansible_host: "{{ ansible_host }}"

- name: 'Install packages for Python'
  apt: name={{ item}} state=present update_cache=yes
  with_items:
    - python-pip
    - python-dev
    - python3-dev
    - python3
    - python3-pip

