#!/bin/bash
if (( $# == 0 )); then
	echo "This will do a dry-run, use -y to action"
	ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook update.yml -i hosts --ask-pass --become --check
else
	if [[ $1 -eq "-y" ]]; then
	  ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook update.yml -i hosts --ask-pass --become
	fi
fi

